import extractZip from "extract-zip";
import { createWriteStream } from "node:fs";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { pipeline } from "node:stream/promises";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
let packageJson;
try {
	packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
} catch (error) {
	throw new Error("Could not read package.json", { cause: error });
}
const version = packageJson.pdfjs?.version;

if (!version) {
	throw new Error("Missing package.json pdfjs.version");
}

const url = `https://github.com/mozilla/pdf.js/releases/download/v${version}/pdfjs-${version}-dist.zip`;
const tmpDir = join(root, ".tmp", "pdfjs-sync");
const zipPath = join(tmpDir, `pdfjs-${version}-dist.zip`);
const extractDir = join(tmpDir, "extract");
const targetDir = join(root, "pdfjs");

process.stdout.write(`Downloading PDF.js ${version}\n`);
process.stdout.write(`${url}\n`);

await rm(tmpDir, { recursive: true, force: true });
await mkdir(extractDir, { recursive: true });

const response = await fetch(url);
if (!response.ok || !response.body) {
	throw new Error(
		`Failed to download PDF.js: ${response.status} ${response.statusText}`,
	);
}

await pipeline(response.body, createWriteStream(zipPath));
await extractZip(zipPath, { dir: extractDir });

// The release zip currently extracts build/, web/, and LICENSE at its root.
const sourceDir = extractDir;

await rm(targetDir, { recursive: true, force: true });
await mkdir(targetDir, { recursive: true });

await cp(join(sourceDir, "build"), join(targetDir, "build"), {
	recursive: true,
});
await cp(join(sourceDir, "web"), join(targetDir, "web"), { recursive: true });
await cp(join(sourceDir, "LICENSE"), join(targetDir, "LICENSE"));

// Keep the committed viewer payload small. Source maps and the bundled demo PDF are
// useful for PDF.js development, but this site only needs the runtime viewer assets.
await Promise.all([
	rm(join(targetDir, "build", "pdf.mjs.map"), { force: true }),
	rm(join(targetDir, "build", "pdf.sandbox.mjs.map"), { force: true }),
	rm(join(targetDir, "build", "pdf.worker.mjs.map"), { force: true }),
	rm(join(targetDir, "web", "viewer.mjs.map"), { force: true }),
	rm(join(targetDir, "web", "compressed.tracemonkey-pldi-09.pdf"), {
		force: true,
	}),
]);

await writeFile(
	join(targetDir, "VERSION"),
	`PDF.js ${version}\nSource: ${url}\nGenerated by: pnpm sync:pdfjs\n`,
);

await rm(tmpDir, { recursive: true, force: true });

process.stdout.write(`Synced PDF.js ${version} into ./pdfjs\n`);
